### PR TITLE
fix(Android) solving the problem with starting the service on Android OS version 12+ (#181)

### PR DESCRIPTION
**Pull request by lesleysin**
Register background service in package AndroidManifest.xml
https://reactnative.dev/docs/headless-js-android?android-language=kotlin

Related [issue](https://github.com/Rapsssito/react-native-background-actions/issues/181)

### CODE REVIEW

**Comment by Rapsssito** [comment]
@lesleysin, this is already described in https://github.com/Rapsssito/react-native-background-actions/blob/master/INSTALL.md. Do you mean that you do not need to add it to the user's AndroidManifest.xml, but instead to react-native-background-task AndroidManifest?

**Comment by lesleysin** [comment]
@Rapsssito Yes, I'm assuming it should work exactly as you described.
The rules for merging manifests for packages are described [here](https://developer.android.com/build/manage-manifests)

**Comment by Rapsssito** [comment]
Thanks! Then, I will update the documentation. Thanks for the PR!

**Comment by LucasHimelfarb** [comment]
@Rapsssito this fix si related with https://github.com/Rapsssito/react-native-background-actions/issues/168 ?

**Pull request merged**
