### PR TITLE
fix: Fix #61 when React context was null

### LINKED ISSUE #61: Occasional Background task crash in production
My Sentry instance is catching occasional failures to start the background task.

https://sentry.ecoeats.uk/share/issue/7cf6f7ee88ee454ca3e73647693f83e3/

The issue appears to be that the buildNotification method constructs an Intent but the constructor returns null. I'm unable to replicate this issue in a dev environment. 

`notificationIntent = new Intent(context, context.getCurrentActivity().getClass());`

Is the issue possibly that I'm attempting to start a task that is in the background already / the calling function is already in the background?

### PR DESCRIPTION
**Pull request by ArsalImam**
Fixes #61 React context was getting null

### CODE REVIEW

**Comment by Rapsssito** [comment]
@ArsalImam, have you been able to reproduce the issue with and without your fix?

**Comment by ArsalImam** [comment]
@Rapsssito, This is a random crash, it comes to me twice but I am not sure about the actual steps to reproduce this crash. 
FYI, on Crashlytics, it is a bit frequent.

**Comment by Rapsssito** [comment]
@ArsalImam, have you tested this fix? Does it reduce the crashes?

**Comment by rewhex** [comment]
With this fix, "open with" dialog is opening on my OnePlus, will publish my app with this instead:
`Intent notificationIntent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);
    notificationIntent.setComponent(new ComponentName("com.mypackage", "com.mypackage.MainActivity"));
    notificationIntent.setPackage("com.mypackage");`

**Comment by ArsalImam** [comment]
@Rapsssito I have verified this fix, this crash is not anymore in my app's production environment.

**Comment by ArsalImam** [comment]
@Rapsssito I have successfully verified the fix in #89 in the production environment (after 100% rollout - last week). Till now, we didn't receive any occurrence of this issue (currently, 2k+ users are using the latest version of the app).

**Pull request merged**
